#!/usr/bin/env bash

DOTFILES=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# ZSH configs
ln -sf "$DOTFILES/zsh/aliases" "$HOME/.aliases"
ln -sf "$DOTFILES/zsh/zshrc" "$HOME/.zshrc"
ln -sf "$DOTFILES/zsh/p10k.zsh" "$HOME/.p10k.zsh"

# Git configs
ln -sf "$DOTFILES/git/gitconfig" "$HOME/.gitconfig"
ln -sf "$DOTFILES/git/gitignore_global" "$HOME/.gitignore_global"

# Install custom bin scripts
rm -rf "{$HOME/bin}"
ln -s "$DOTFILES/bin" "$HOME/bin"

# When we have bin/local scripts we want, use this symlink
#ln -sf "$DOTFILES/bin/local/*" "$HOME/.local/bin"

# Install Oh-My-ZSH if not already installed
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
    echo "Oh My ZSH is already installed!"
fi

# Install composer if not already installed
if [ ! -f "$HOME/bin/composer"]; then
    sh "$DOTFILES/scripts/install-composer.sh"
else
    echo "Composer is already installed!"
fi

sh "$DOTFILES/zsh/install_plugins.sh"