#!/usr/bin/env bash

# A simple install script for Debian systems, including Raspberry Pi,
# it will handle gathering dependencies and tools for a first time install.

install_dependencies() {
    # Install core dependencies
    sudo apt install -y build-essential ca-certificates curl git gnupg2 openssl vim wget

    # Install tools
    sudo apt install -y batcat cowsay direnv eza fd-find fzf jq lolcat neovim nmap rclone ripgrep tmux
}

install_tools() {
    # Set up dependency list
    TOOLS=(
        "bun"
        "docker"
        "zoxide"
    )
    INSTALL_COMMANDS=(
        "curl -fsSL https://bun.sh/install | bash"
        "curl -sSL https://get.docker.com | sh && sudo usermod -aG docker $USER"
        "curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh"
    )

    for i in "${!TOOLS[@]}"; do
        tool="${TOOLS[i]}"
        install_command="${INSTALL_COMMANDS[i]}"

        if ! command -v "$tool" >/dev/null 2>&1; then
            echo "Installing $tool..."
            eval "$install_command"
        else
            echo "$tool is already installed. Continuing..."
        fi
    done
}

install_nvm() {
    LATEST_VERSION=$(curl -s "https://api.github.com/repos/nvm-sh/nvm/releases/latest" | grep -o '"tag_name": "[^"]*"' | sed 's/"tag_name": "\(.*\)"/\1/')

    if command -v nvm >/dev/null 2>&1; then
        echo "Updating NVM to version $LATEST_VERSION"
    else
        echo "Installing NVM version $LATEST_VERSION"
    fi

    curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/$LATEST_VERSION/install.sh" | bash
    echo "NVM installed."
}

set_keyrings() {
    echo "Setting up keyrings..."

    # Create the keyrings directory if it doesn't exist
    sudo mkdir -p /etc/apt/keyrings

    # Create a list of GPG keys to download
    KEYURLS=(
        "https://raw.githubusercontent.com/eza-community/eza/main/deb.asc"
    )
    KEYNAMES=(
        "gierens"
    )
    KEYREPOS=(
        "http://deb.gierens.de"
    )

    # Download each GPG key and add it to the keyring
    for i in "${!KEYURLS[@]}"; do
        url="${KEYURLS[i]}"
        name="${KEYNAMES[i]}"
        repo="${KEYREPOS[i]}"

        # 1. Get the key
        echo "Downloading key $name from: $url"
        wget -qO- "$url" | sudo gpg --dearmor -o "/etc/apt/keyrings/${name}.gpg"

        # 2. Add the repository to the sources list
        echo "deb [signed-by=/etc/apt/keyrings/${name}.gpg] ${repo} stable main" | sudo tee "/etc/apt/sources.list.d/${name}.list"

        # 3. Set the permissions
        sudo chmod 644 "/etc/apt/keyrings/${name}.gpg" "/etc/apt/sources.list.d/${name}.list"
    done

    # Update the package list
    sudo apt update

    echo "Keyring setup complete."
}

# Do a system update
echo "Preparing system update..."
sudo apt update

echo "Running update..."
sudo apt -y upgrade

set_keyrings
install_dependencies
install_tools
install_nvm

# Cleanup
echo "Cleaning up..."
sudo apt autoremove -y
sudo apt clean

# Symlink to bind fd-find to fd instead
mkdir -p "$HOME/.local/bin/local"
ln -s "$(which fdfind)" "$HOME/.local/bin/local/fd"
